# Aula 11: Introdução ao Pandas e Ciência de Dados

Na aula passada, aprendemos a salvar tabelas (CSV). Mas ler um CSV e analisá-lo usando `for` e `if` puros, célula por célula, dá um trabalho gigantesco.

Para isso, a comunidade criou a biblioteca mais famosa de Data Science do ecossistema: o **Pandas**.

## 1. O que é o Pandas e o Kaggle?

*   **Pandas**: É o nosso "Excel com esteróides" dentro do Python. Ele carrega planilhas gigantes em segundos e nos deixa fazer contas complexas com 1 linha de código.
*   **Kaggle**: É o maior site de Ciência de Dados do mundo. Lá podemos baixar planilhas (CSVs) reais de todos os temas possíveis (filmes, saúde, economia) para treinar.

*(Observação: Você precisará instalar o Pandas para rodar os códigos abaixo. No terminal ou célula rode: `!pip install pandas`)*

In [1]:
!pip install pandas
import pandas as pd # Importando e dando um 'apelido' super comum: pd

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

## 2. Lendo um CSV como DataFrame

A estrutura principal do Pandas é o **DataFrame** (que é o nome elegante para "Tabela").

In [2]:
# Vamos criar um CSV básico aqui primeiro (ou ler o turma.csv da aula passada)
import csv
with open("loja_teste.csv", "w", newline='') as f:
    writer = csv.writer(f)
    writer.writerows([
        ["Produto", "Preco", "Quantidade"],
        ["Caderno", 15.50, 40],
        ["Caneta", 2.50, 150],
        ["Mochila", 89.90, 10]
    ])

# Lendo a tabela inteira com 1 linha de Pandas!
df = pd.read_csv("loja_teste.csv")
df  # No Jupyter, é só digitar a variável no final da célula para mostrar a tabela bonitinha

   Produto  Preco  Quantidade
0  Caderno   15.5          40
1   Caneta    2.5         150
2  Mochila   89.9          10

## 3. Explorando os Dados

Com a tabela em mãos (`df`), o Pandas tem várias "habilidades" mágicas.

In [3]:
print("1. Quantidade de Linhas e Colunas:", df.shape)
print("\n2. Ver os primeiros itens:")
display(df.head(2))
print("\n3. Descrição Estatística (Média, Max, Min):")
display(df.describe())

1. Quantidade de Linhas e Colunas: (3, 3)

2. Ver os primeiros itens:

   Produto  Preco  Quantidade
0  Caderno   15.5          40
1   Caneta    2.5         150

3. Descrição Estatística (Média, Max, Min):

           Preco  Quantidade
count   3.000000    3.000000
mean   35.966667   66.666667
std    47.157749   73.711148
min     2.500000   10.000000
25%     9.000000   25.000000
50%    15.500000   40.000000
75%    52.700000   95.000000
max    89.900000  150.000000

## 4. Manipulando Colunas e Filtros

Para pegar uma coluna inteira, usamos como se fosse a chave de um Dicionário: `df['Preco']`.

In [4]:
# O Pandas é vetorizado. Ele deixa fazer conta na coluna INTEIRA de uma só vez
df['Faturamento_Bruto'] = df['Preco'] * df['Quantidade']

print("Tabela com a nova coluna Matemática:")
display(df)

# Filtrando!
print("\nMostrando APENAS produtos que custam menos de 30 reais:")
display(df[df['Preco'] < 30])

Tabela com a nova coluna Matemática:

   Produto  Preco  Quantidade  Faturamento_Bruto
0  Caderno   15.5          40              620.0
1   Caneta    2.5         150              375.0
2  Mochila   89.9          10              899.0

Mostrando APENAS produtos que custam menos de 30 reais:

   Produto  Preco  Quantidade  Faturamento_Bruto
0  Caderno   15.5          40              620.0
1   Caneta    2.5         150              375.0

---
## Lista de Exercícios

### Desafio 1: Tabela de Notas
Crie na mão um pequeno CSV (usando o módulo nativo ou pelo Bloco de Notas) contendo `Aluno, Portugues, Matematica`. Em seguida:
1. Use `pd.read_csv` para carregá-lo.
2. Crie uma coluna nova `Media` como a soma das duas dividida por 2.
3. Filtre na tela apenas os alunos com média >= 7.

In [5]:
import pandas as pd
import csv

# 1. Crie na mão um pequeno CSV
csv_filename = "notas_alunos.csv"
with open(csv_filename, "w", newline='') as f:
    writer = csv.writer(f)
    writer.writerows([
        ["Aluno", "Portugues", "Matematica"],
        ["Ana", 8, 9],
        ["Bruno", 6, 7],
        ["Carla", 7, 7],
        ["Daniel", 9, 6],
        ["Eduardo", 5, 8]
    ])

# 2. Use pd.read_csv para carregá-lo.
df_notas = pd.read_csv(csv_filename)

# 3. Crie uma coluna nova Media como a soma das duas dividida por 2.
df_notas['Media'] = (df_notas['Portugues'] + df_notas['Matematica']) / 2

# 4. Filtre na tela apenas os alunos com média >= 7.
alunos_aprovados = df_notas[df_notas['Media'] >= 7]
display(alunos_aprovados)

    Aluno  Portugues  Matematica  Media
0     Ana          8           9    8.5
2   Carla          7           7    7.0
3  Daniel          9           6    7.5